<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TruckTaxPro.Data\TruckTaxPro.Data.csproj" />
    <ProjectReference Include="..\TruckTaxPro.Domain\TruckTaxPro.Domain.csproj" />
  </ItemGroup>

</Project>
